databases:
  - name: scpi_db
    databaseName: scpi
    user: scpi_user

services:
  - type: web
    name: scpi
    env: python
    buildCommand: "./build.sh"
    startCommand: "cd scpi && gunicorn scpi.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: scpi_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4